server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**

eureka:
  client:
    enabled: false