spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # Apply to all paths
            allowedOrigins:
              - "https://fintrak-472601.web.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service-route
          uri: https://user-service-69216980478.us-central1.run.app
          predicates:
            - Path=/api/v1/users/**
          metadata:
            cors:
              allowedOrigins: "https://fintrak-472601.web.app"

eureka:
  client:
    enabled: false