# In application-prod.properties

# This special JDBC URL uses the Google Cloud Socket Factory for secure connections
# Explicitly enable Google Cloud SQL auto-configuration for the 'prod' profile
spring.cloud.gcp.sql.enabled=true
# Explicitly enable Google Cloud Secret Manager for the 'prod' profile
spring.cloud.gcp.secretmanager.enabled=true
spring.cloud.gcp.sql.instance-connection-name=fintrak-472601:us-central1:fintrack-postgres-instance
spring.cloud.gcp.sql.database-name=fintrack_db

spring.datasource.username=postgres
spring.datasource.password=${sm://projects/fintrak-472601/secrets/fintrack-db-password}


# We don't need the URL anymore, the starter configures it for us
# spring.datasource.url=...

# Temporary property for debugging the Secret Manager connection
fintrack.test.secret=${sm://projects/fintrak-472601/secrets/test-secret}